### ISSUE TITLE
Problems in compiling to Raspberry Pi via the package on PyPi

### ISSUE THREAD

**Issue by amarchino** [mbientlab/Warble#1]
Greetings!

We are trying to compile Your project via pip so as to use the Metawear-SDK-Python on a Raspberry Pi 3 B+.
By following the instructions in the downstream repository (ie: the Python SDK), we have encountered a problem in building the Warble package.

By use of `pip` to compile, we found that it tries to download the package posted on [PythonHosted](https://files.pythonhosted.org/packages/07/6a/bd90b1258fdde100bbc9e5b0740c6c2c9b4c7825d2f808dc6ff8c8487862/warble-1.0.2.tar.gz) that actually has the already compiled .o files inside.
These files were compiled for X86-64 (information obtained by `file clibs/warble/deps/libblepp/src/att.o'), and therefore are not compatible with the ARM architecture of the Raspberry.

Given that these files are a dependency of the package, and that pip seems not to be configurable to first call `make clean` so as to ensure that the sources are recompiled, we ask for informations on how to install Your library for use in other packages.

We attach a file with the compilation result, so as to give a proper context for the problem we found.

[tryinst1_err_1.txt](https://github.com/mbientlab/Warble/files/2128140/tryinst1_err_1.txt)

Thanks!

**Comment by scaryghost** [comment]
This is an issue with the Python wrappers around the project, not the C code itself.  Please file issues under the appropriate repo.
https://github.com/mbientlab/PyWarble
