### ISSUE TITLE
Build Warble?

### ISSUE THREAD

**Issue by thoraxmax** [mbientlab/Warble#4]
Hi, When i try to build the environment for Python SDK by building Warble I get this error in Command Prompt (as admin):
https://github.com/mbientlab/Warble

Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>MSBuild.exe warble.sln
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: warble.sln

C:\WINDOWS\system32>

I get similar errors when I try to build the solution in Visual Studio 2017:
1>------ Rebuild All started: Project: warble, Configuration: Debug x64 ------
1>Object reference not set to an instance of an object.
2>------ Rebuild All started: Project: example-scanner, Configuration: Debug x64 ------
2>Object reference not set to an instance of an object.
2>Error: Object reference not set to an instance of an object.
3>------ Rebuild All started: Project: example-connect, Configuration: Debug x64 ------
3>Object reference not set to an instance of an object.
3>Error: Object reference not set to an instance of an object.
4>------ Rebuild All started: Project: example-read-dev-info, Configuration: Debug x64 ------
4>Object reference not set to an instance of an object.
4>Error: Object reference not set to an instance of an object.
========== Rebuild All: 0 succeeded, 4 failed, 0 skipped ==========

I have installed Python 3.7, FCU Windows 10 SDK (10.0.16299.0) and pip also.

What am I doing wrong? Thank you.

**Comment by scaryghost** [comment]
The first issue is pretty self explanatory, as indicated by the error message:

    MSBUILD : error MSB1009: Project file does not exist.

Regarding your VS build, post the filename and line number referenced by that error message.

**Comment by thoraxmax** [comment]
Thank you. I am new to this, but I am thankful for you help.
But the warble.sln exist? even if i specify directory I get the error:
`Microsoft Windows [Version 10.0.17134.228]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>MSbuild.exe 'C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln'
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: 'C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln'

C:\WINDOWS\system32>`

**Comment by thoraxmax** [comment]
if i run from the folder with power shell I instead get this:

PS C:\Users\thors\Desktop\Warble-master\vs2017>
PS C:\Users\thors\Desktop\Warble-master\vs2017> msbuild warble.sln
Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 2018-09-05 11:41:20.
Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" (1) is building "C:\Users\thors\Desktop\Warble-master\
vs2017\warble.vcxproj" (2) on node 1 (default targets).
GenerateLibDef:
  ..\bin\generate_version.bat
  'git' is not recognized as an internal or external command,
  operable program or batch file.
  Missing operand.
  ..
InitializeBuildStatus:
  Touching "x64\Debug\warble.tlog\unsuccessfulbuild".
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\CL.exe /c /AI
  "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\vcpackages" /AI"C:\Program Files (x86)\
  Windows Kits\10\UnionMetadata\10.0.16299.0" /ZI /JMC /ZW /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D WARBLE_DLL
  _EXPORTS /D API_WIN10 /D _DEBUG /D WARBLE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc
   /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"x64\Debug\\" /Fd"x64\Debug\vc141.pdb
  " /Gd /TP /FC /errorReport:queue /Zc:twoPhase- ..\src\warble\cpp\lib.cpp
  lib.cpp
c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(2): error C2001: newline in constant [C:\Users\thors\Desk
top\Warble-master\vs2017\warble.vcxproj]
c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(3): error C4430: missing type specifier - int assumed. No
te: C++ does not support default-int [C:\Users\thors\Desktop\Warble-master\vs2017\warble.vcxproj]
c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(3): error C2146: syntax error: missing ';' before identif
ier 'program' [C:\Users\thors\Desktop\Warble-master\vs2017\warble.vcxproj]
c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(5): error C2001: newline in constant [C:\Users\thors\Desk
top\Warble-master\vs2017\warble.vcxproj]
Done Building Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.vcxproj" (default targets) -- FAILED.

Done Building Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" (default targets) -- FAILED.


Build FAILED.

"C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" (default target) (1) ->
"C:\Users\thors\Desktop\Warble-master\vs2017\warble.vcxproj" (default target) (2) ->
(ClCompile target) ->
  c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(2): error C2001: newline in constant [C:\Users\thors\De
sktop\Warble-master\vs2017\warble.vcxproj]
  c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(3): error C4430: missing type specifier - int assumed.
Note: C++ does not support default-int [C:\Users\thors\Desktop\Warble-master\vs2017\warble.vcxproj]
  c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(3): error C2146: syntax error: missing ';' before ident
ifier 'program' [C:\Users\thors\Desktop\Warble-master\vs2017\warble.vcxproj]
  c:\users\thors\desktop\warble-master\src\warble\cpp\lib_def.h(5): error C2001: newline in constant [C:\Users\thors\De
sktop\Warble-master\vs2017\warble.vcxproj]

    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:02.93
PS C:\Users\thors\Desktop\Warble-master\vs2017>

**Comment by scaryghost** [comment]
Again, your error is self-explanatory.

> PS C:\Users\thors\Desktop\Warble-master\vs2017> msbuild warble.sln
> Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> Build started 2018-09-05 11:41:20.
> Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" on node 1 (default targets).
> ValidateSolutionConfiguration:
> Building solution configuration "Debug|x64".
> Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" (1) is building "C:\Users\thors\Desktop\Warble-master
> vs2017\warble.vcxproj" (2) on node 1 (default targets).
> GenerateLibDef:
> ..\bin\generate_version.bat
> **'git' is not recognized as an internal or external command,**
> operable program or batch file.
> Missing operand.

**Comment by scaryghost** [comment]
> PS C:\Users\thors\Desktop\Warble-master\vs2017> msbuild warble.sln
> Microsoft (R) Build Engine version 15.8.168+ga8fba1ebd7 for .NET Framework
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
> Build started 2018-09-05 11:41:20.
> Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" on node 1 (default targets).
> ValidateSolutionConfiguration:
> Building solution configuration "Debug|x64".
> Project "C:\Users\thors\Desktop\Warble-master\vs2017\warble.sln" (1) is building "C:\Users\thors\Desktop\Warble-master
> vs2017\warble.vcxproj" (2) on node 1 (default targets).
> GenerateLibDef:
> ..\bin\generate_version.bat
> **'git' is not recognized as an internal or external command,**
> operable program or batch file.
> Missing operand.

Please re-read the build section.  It does not look like you have retrieved the source code as instructed.
https://github.com/mbientlab/Warble#build

**Comment by scaryghost** [comment]
Warble doesn't have a cmake build file.  What command(s) did you execute?

**Comment by scaryghost** [comment]
What git commands did you run?

**Comment by thoraxmax** [comment]
Thank you I now succeeded. I believe it was the path that did not found it. I specified the path in "source" folder.

Solved!
