### ISSUE TITLE
name, metawear service and manufacturer data empty?

### ISSUE THREAD

**Issue by dijkstrah** [mbientlab/Warble#5]
Cloned 1.1.5, on windows 10, Visual Studio 2017, SDK 10.0.17763.0, output is like this for all devices found in the example-scanner. 

mac: 51:70:61:5A:61:B2
name:
rssi: -66 dBm
metawear service? 0
mbientlab manufacturer data? false

**Comment by scaryghost** [comment]
What is wrong with that output?

**Comment by dijkstrah** [comment]
This is just an example. All output is similar in that mac and rssi have a value and the rest not. I expected a field like name to have a value as well, but your answer seems to express this is normal. I was just wondering.

**Comment by scaryghost** [comment]
That depends on your device.  If it's not advertising a name, then there's nothing to set in that field.
