### ISSUE TITLE
Read Dev Info Example not finding UUID characteristics

### ISSUE THREAD

**Issue by nhobson99** [mbientlab/Warble#6]
I've been trying to get the demos to work. I know something works because the scan demo picks up my bluetooth LE Arduino. But it can't seem to find any device info and pauses after the first try. Am I doing anything wrong?

For more info, I'm using a cheap "Panda BT 4.0" USB dongle on the PC side (Windows 10) and using Visual Studio 2019. The Arduino is a Keywishbot Bluetooth Nano BLE module. I don't have any other BLE modules to test with except a second, identical Arduino. I've also tried a few Windows BLE scanner apps that seem to pick up the characteristics alright, so it should be working. Any tips would be appreciated, thanks.

**Comment by scaryghost** [comment]
There's very little information to work with here.

* Log variable values  
* Find out where in the code this pause you are talking about happens  
* What characteristics did the other scanner apps detect?

**Comment by nhobson99** [comment]
![problem](https://user-images.githubusercontent.com/46683481/61911612-fb75a800-af05-11e9-9527-2980eb24cba7.png)
This is all the data I get out of an app called Bluetooth LE Explorer from the Windows store. SimpleKeyState at the very bottom is the data I'm trying to read off the Arduino board, but can't access.

Running connect.cpp yields the following:
`C:\Users\nhobs\source\repos\Warble\vs2017\Debug>example-connect.exe a8:10:87:51:b4:9b`
`Connecting to a8:10:87:51:b4:9b`
`You done fucked up`
`C:\Users\nhobs\source\repos\Warble\vs2017\Debug>`

Similarly, running read_dev_info.cpp yields this:
`C:\Users\nhobs\source\repos\Warble\vs2017\Debug>example-read-dev-info.exe a8:10:87:51:b4:9b`
`00002a26-0000-1000-8000-00805f9b34fb: not found`

And from there I'm not quite sure where to go. I did manage to use a bluetooth LE peripheral emulator on my phone, which acts like a BLE smart device. Connect.cpp does work with my phone (Am I connected? 1) but read_dev_info.cpp still says <UUID #>: not found.

**Comment by scaryghost** [comment]
ok, I see the code does not progress if uuid is not found:
https://github.com/mbientlab/Warble/blob/1.1.5/example/read_dev_info.cpp#L25

Try this version of read_dev_info.cpp from the [noppl](https://github.com/mbientlab/Warble/blob/noppl/example/read_dev_info.cpp) branch.

The more interesting thing here is why that characteristic is not found since the other BLE app can see it.
