### ISSUE TITLE
LNK2019 unresolved external symbol...

### ISSUE THREAD

**Issue by adichattopadhyay** [mbientlab/Warble#7]
I added the connect example to my code to try and test out the Warble library, when I ran it I ran into this error:
`unresolved external symbol _warble_gatt_create referenced in function _main
unresolved external symbol _warble_gatt_connect_async referenced in function _main
unresolved external symbol _warble_gatt_disconnect referenced in function _main
unresolved external symbol _warble_gatt_on_disconnect referenced in function _main
unresolved external symbol _warble_gatt_is_connected referenced in function "public: void __thiscall <lambda_482e9b2f9ff0ab3140f2e29f203c3bd0>::operator()(void *,struct WarbleGatt *,char const *)const " (??R<lambda_482e9b2f9ff0ab3140f2e29f203c3bd0>@@QBEXPAXPAUWarbleGatt@@PBD@Z)
`
Here is main.cpp:
`
#include <Windows.h>

#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <vector> 
#include <chrono>
#include <future>
#include <iostream>
#include <stdexcept>
#include <thread>
#include <utility>

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <SOIL2/SOIL2.h>
#include <json-c/json.h>
#include <glm/gtc/quaternion.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/gtx/string_cast.hpp>

#include "Model.h"
#include "camera.h"
#include "Shader.h"
#include "stdafx.h"
#include "Warble/warble.h"
#include "Warble/scanner.h"

#pragma comment(lib, "opengl32.lib")
#define _CRT_SECURE_NO_WARNINGS
#pragma warning (disable : 4996)

// Properties
const GLuint WIDTH = 1000, HEIGHT = 1000;
int SCREEN_WIDTH, SCREEN_HEIGHT;

// Function prototypes
void KeyCallback(GLFWwindow* window, int key, int scancode, int action, int mode);
void MouseCallback(GLFWwindow* window, double xPos, double yPos);
void DoMovement();

// Camera
Camera camera(glm::vec3(0.0f, 0.0f, 15.3f));
bool keys[1024];
GLfloat lastX = 400, lastY = 300;
bool firstMouse = true;

GLfloat deltaTime = 0.0f;
GLfloat lastFrame = 0.0f;

bool allowCamera = true;
bool animationStart = false;
int counter = 0;
int main()
{
	string deviceAddress;
	cout << "What is the MAC Address of the Device?\n";
	getline(cin, deviceAddress);
	auto gatt = warble_gatt_create(deviceAddress.c_str());
	for (int i = 0; i < 3; i++) {
		promise<void> connect_task;
		cout << "Connecting to " << deviceAddress << endl;
		warble_gatt_connect_async(gatt, &connect_task, [](void* context, WarbleGatt* caller, const char* value) {
			auto task = (promise<void>*) context;

			if (value != nullptr) {
				cout << "Connection failed" << endl;
				task->set_exception(make_exception_ptr(runtime_error(value)));
			}
			else {
				cout << "Am I connected? " << warble_gatt_is_connected(caller) << endl;

				this_thread::sleep_for(5s);
				task->set_value();
			}
			});
		connect_task.get_future().get();
		promise<int32_t> dc_task;
		cout << "Disconnecting..." << endl;
		warble_gatt_on_disconnect(gatt, &dc_task, [](void* context, WarbleGatt* caller, int32_t status) {
			((promise<int32_t>*) context)->set_value(status);
			});
		warble_gatt_disconnect(gatt);
		cout << "disconnected, status = " << dc_task.get_future().get() << endl;

		cout << "Am I connected? " << warble_gatt_is_connected(gatt) << endl;
	}
        return 0;
}
`

**Comment by scaryghost** [comment]
This is not a Warble issue.
http://lmgtfy.com/?q=visual+studio+unresolved+external+symbol+lnk2019
